{"metadata":{"externalID":"AdyenAuthentication","symbolKind":"module","roleHeading":"Framework","role":"collection","modules":[{"name":"AdyenAuthentication"}],"title":"AdyenAuthentication"},"hierarchy":{"paths":[[]]},"abstract":[{"text":"AdyenAuthentication SDK Provides reusable and easy to use two factor authentication","type":"text"},{"text":" ","type":"text"},{"text":"for security sensitive use cases like banking, issuing and PSD2 strong customer authentication.","type":"text"}],"topicSections":[{"generated":true,"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/AuthenticationService"]},{"generated":true,"anchor":"Protocols","title":"Protocols","identifiers":["doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/AuthenticationServiceProtocol","doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/DeviceSupportCheckerProtocol"]},{"generated":true,"anchor":"Structures","title":"Structures","identifiers":["doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/DeviceCheckConfiguration","doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/DeviceSupportChecker","doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/PassKeyConfiguration"]},{"generated":true,"anchor":"Enumerations","title":"Enumerations","identifiers":["doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/AdyenAuthenticationError"]}],"variants":[{"paths":["\/documentation\/adyenauthentication"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenauthentication"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"It leverages the new ","type":"text"},{"type":"codeVoice","code":"FIDO"},{"text":" security protocol and its support on modern apple devices,","type":"text"},{"text":" ","type":"text"},{"text":"to protect against app binary tampering, leveraging the biometric capabilities on modern apple devices,","type":"text"},{"text":" ","type":"text"},{"text":"making authentication more frictionless while providing more security through multi-factor","type":"text"},{"text":" ","type":"text"},{"text":"authentication.","type":"text"}]},{"level":2,"anchor":"Usage","type":"heading","text":"Usage:"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Initialization","type":"text"},{"text":" ","type":"text"},{"text":"There are two configuration options.","type":"text"}]}]}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Using device check apis"}]}]}]},{"type":"codeListing","syntax":"Swift","code":["let configuration = AuthenticationService.Configuration(localizedRegistrationReason: \/\/ Text explaining to the user why we need their biometrics while registration,","                                                        localizedAuthenticationReason: \/\/ Text explaining to the user why we need their biometrics while authentication.","                                                        appleTeamIdentifier: \/\/ The Apple registered development team identifier.)","self.authenticationService =  AuthenticationService(configuration: configuration)"]},{"type":"orderedList","start":2,"items":[{"content":[{"inlineContent":[{"text":"Using Apple passkeys","type":"text"}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":"Swift","code":["let configuration = AuthenticationService.PassKeyConfiguration(","                    relyingPartyIdentifier: \"com.example.com\",","                    displayName: \"App name\",","                    consecutiveApprovalCancellationsLimit: Int?","                )","self.authenticationService = AuthenticationService(configuration: configuration)"]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Check Device support"}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":"Swift","code":["let deviceSupport = try authenticationService.checkSupport()"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This call will throw an error in case the current device is not supported, otherwise returns an opaque string payload that needs to be sent to backend API depending on the use case."}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Check whether Device is registered","type":"text"}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":"Swift","code":["authenticationService.isDeviceRegistered(withAuthenticationInput: input \/*The opaque string sdk input*\/) { [weak self] result in","    switch result {","    case let .success(isRegistered):","        \/\/\/ output is a Boolean indicating whether the current device is registered,","        \/\/\/ then you can call `authenticate` function below.","    case let .failure(error):","        \/\/\/ Error raised,","        \/\/\/ for example if the device is not protected by either pass code, face Id, or fingerprint, or if device is not registered,","        \/\/\/ then you can call `register` function below.","    }","}","","\/\/ OR you can also use the async version of this function:","","let isDeviceRegistered = try await authenticationService.isDeviceRegistered(withAuthenticationInput: input \/*The opaque string sdk input*\/)"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For first time registration:"}]}]}]},{"type":"codeListing","syntax":"Swift","code":["authenticationService.register(withRegistrationInput: input \/*The opaque string sdk input*\/) { [weak self] result in","    switch result {","    case let .success(output):","        \/\/\/ output is an opaque string that should be sent to Adyen backend API (depending on the use case) to be validated for registration to be finalized.","    case let .failure(error):","        \/\/\/ Failure to register the device, for example if the device is not protected by either pass code, face Id, or fingerprint.","    }","}","","\/\/ OR you can also use the async version of this function:","","let sdkOutput = try await authenticationService.register(withRegistrationInput: input \/*The opaque string sdk input*\/)"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For authentication:"}]}]}]},{"type":"codeListing","syntax":"Swift","code":["authenticationService.authenticate(withAuthenticationInput: input \/*The opaque string sdk input*\/) { result in","    switch result {","    case let .success(output):","        \/\/\/ output is an opaque string that should be sent to Adyen backend API (depending on the use case) to be validated for authentication to be finalized.","    case let .failure(error):","        \/\/\/ Failure to authenticate, which usually means that the current account is not registered.","    }","}","","\/\/ OR you can also use the async version of this function:","","let sdkOutput = try await authenticationService.authenticate(withAuthenticationInput: input \/*The opaque string sdk input*\/)"]}]}],"references":{"doc://com.adyen.AdyenAuthentication/documentation/AdyenAuthentication/AdyenAuthenticationVersionNumber":{"title":"AdyenAuthenticationVersionNumber","abstract":[{"text":"Project version number for AdyenAuthentication.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/adyenauthentication\/adyenauthenticationversionnumber","identifier":"doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/AdyenAuthenticationVersionNumber","fragments":[{"text":"AdyenAuthenticationVersionNumber","kind":"identifier"}],"role":"symbol"},"doc://com.adyen.AdyenAuthentication/documentation/AdyenAuthentication/AuthenticationServiceProtocol":{"identifier":"doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/AuthenticationServiceProtocol","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Describes an authentication serivce."}],"title":"AuthenticationServiceProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationServiceProtocol"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationServiceProtocol"}],"url":"\/documentation\/adyenauthentication\/authenticationserviceprotocol"},"doc://com.adyen.AdyenAuthentication/documentation/AdyenAuthentication/AdyenAuthenticationError":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdyenAuthenticationError"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdyenAuthenticationError"}],"role":"symbol","url":"\/documentation\/adyenauthentication\/adyenauthenticationerror","identifier":"doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/AdyenAuthenticationError","abstract":[{"type":"text","text":"An Error thrown by "},{"type":"codeVoice","code":"AuthenticationService"},{"type":"text","text":"."}],"title":"AdyenAuthenticationError","type":"topic"},"doc://com.adyen.AdyenAuthentication/documentation/AdyenAuthentication/DeviceSupportChecker":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/DeviceSupportChecker","navigatorTitle":[{"kind":"identifier","text":"DeviceSupportChecker"}],"url":"\/documentation\/adyenauthentication\/devicesupportchecker","abstract":[{"type":"text","text":"Checks the device support."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceSupportChecker"}],"title":"DeviceSupportChecker","role":"symbol"},"doc://com.adyen.AdyenAuthentication/documentation/AdyenAuthentication/DeviceSupportCheckerProtocol":{"type":"topic","abstract":[{"type":"text","text":"An object that checks the device support."}],"navigatorTitle":[{"text":"DeviceSupportCheckerProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/DeviceSupportCheckerProtocol","title":"DeviceSupportCheckerProtocol","kind":"symbol","role":"symbol","url":"\/documentation\/adyenauthentication\/devicesupportcheckerprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceSupportCheckerProtocol","kind":"identifier"}]},"doc://com.adyen.AdyenAuthentication/documentation/AdyenAuthentication/AdyenAuthenticationVersionString":{"title":"AdyenAuthenticationVersionString","url":"\/documentation\/adyenauthentication\/adyenauthenticationversionstring","identifier":"doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/AdyenAuthenticationVersionString","role":"symbol","abstract":[{"type":"text","text":"Project version string for AdyenAuthentication."}],"kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"AdyenAuthenticationVersionString"}]},"doc://com.adyen.AdyenAuthentication/documentation/AdyenAuthentication":{"title":"AdyenAuthentication","url":"\/documentation\/adyenauthentication","identifier":"doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication","type":"topic","abstract":[{"type":"text","text":"AdyenAuthentication SDK Provides reusable and easy to use two factor authentication"},{"type":"text","text":" "},{"type":"text","text":"for security sensitive use cases like banking, issuing and PSD2 strong customer authentication."}],"role":"collection","kind":"symbol"},"doc://com.adyen.AdyenAuthentication/documentation/AdyenAuthentication/PassKeyConfiguration":{"kind":"symbol","role":"symbol","abstract":[{"text":"The configuration for an authentication service that synchronizes credentials across user’s devices.","type":"text"}],"identifier":"doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/PassKeyConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PassKeyConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PassKeyConfiguration","kind":"identifier"}],"url":"\/documentation\/adyenauthentication\/passkeyconfiguration","title":"PassKeyConfiguration"},"doc://com.adyen.AdyenAuthentication/documentation/AdyenAuthentication/AuthenticationService":{"type":"topic","navigatorTitle":[{"text":"AuthenticationService","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The main authentication service","type":"text"}],"kind":"symbol","url":"\/documentation\/adyenauthentication\/authenticationservice","title":"AuthenticationService","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationService","kind":"identifier"}],"identifier":"doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/AuthenticationService"},"doc://com.adyen.AdyenAuthentication/documentation/AdyenAuthentication/DeviceCheckConfiguration":{"identifier":"doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/DeviceCheckConfiguration","abstract":[{"type":"text","text":"The configuration for a device local authentication service."}],"kind":"symbol","role":"symbol","title":"DeviceCheckConfiguration","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceCheckConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceCheckConfiguration","kind":"identifier"}],"url":"\/documentation\/adyenauthentication\/devicecheckconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/AdyenAuthenticationVersionNumber","doc:\/\/com.adyen.AdyenAuthentication\/documentation\/AdyenAuthentication\/AdyenAuthenticationVersionString"],"anchor":"Variables","generated":true,"title":"Variables"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}