name: Test Swift Package Manager Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
    - master

permissions:
  contents: read

jobs:

  SPM:
    runs-on: macos-15-xlarge
    steps:
    - uses: actions/checkout@v5
    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4'

    - name: Test Swift Package Manager Integration
      run: |
        .github/workflows/Scripts/test-SPM-integration.sh
